import {derivePasswordKey} from './crypto';
import {Actor,defaults,ensure,int,permissions,permit,roles,Settings,str} from '../domain';
import seed from '../../data/menu-seed.json';
import {all,atomic,audit,canonical,Context,Database,guard,hash,Input,insert,json,now,one,parse,Row,s,Stmt,uid} from './db';
const bytes=(s:string)=>Uint8Array.from(atob(s.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0));
const b64=(b:Uint8Array)=>btoa(String.fromCharCode(...b)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
export const token=()=>b64(crypto.getRandomValues(new Uint8Array(32)));
export async function passwordHash(password:string,salt=crypto.getRandomValues(new Uint8Array(16))){const bits=await derivePasswordKey(password,salt);return 'pbkdf2-sha256$600000$'+b64(salt)+'$'+b64(new Uint8Array(bits));}
export async function verify(secret:string,encoded:unknown){if(typeof encoded!=='string')return false;const parts=encoded.split('$');if(parts.length!==4||parts[0]!=='pbkdf2-sha256'||parts[1]!=='600000')return false;const actual=await passwordHash(secret,bytes(parts[2]));let diff=actual.length^encoded.length;for(let i=0;i<actual.length;i++)diff|=actual.charCodeAt(i)^encoded.charCodeAt(i);return diff===0;}
export function cookies(req:Request){return Object.fromEntries((req.headers.get('cookie')||'').split(';').map(v=>v.trim().split(/=(.*)/s).slice(0,2)).filter(x=>x.length===2));}
export function cookie(req:Request,name:string,value:string,httpOnly=true,maxAge=43200){return `${name}=${value}; Path=/; SameSite=Strict; Max-Age=${maxAge}${httpOnly?'; HttpOnly':''}${new URL(req.url).protocol==='https:'?'; Secure':''}`;}
export function sameOrigin(req:Request){ensure(req.headers.get('origin')===new URL(req.url).origin&&req.headers.get('sec-fetch-site')!=='cross-site','Reload the application before trying again.',403,'CSRF');ensure((req.headers.get('content-type')||'').startsWith('application/json'),'JSON request required.',415);}
export async function rateLimit(db:Database,id:string,max=6){const key=await hash(id),start=Date.now(),windowStart=start-15*60e3;await s(db,'INSERT INTO auth_attempts (id,count,window_start) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET count=CASE WHEN window_start<? THEN 1 ELSE count+1 END,window_start=CASE WHEN window_start<? THEN ? ELSE window_start END',key,start,windowStart,windowStart,start).run();const r=await one(db,'SELECT count FROM auth_attempts WHERE id=?',key);ensure(Number(r?.count)<=max,'Too many attempts. Try again after 15 minutes.',429,'RATE_LIMIT');}
export async function settingsFor(db:Database,location:string){const r=await one(db,'SELECT * FROM settings WHERE location_id=?',location);ensure(r,'Restaurant setup is unavailable.',503);return{settings:parse<Settings>(r.data_json,defaults),version:Number(r.version)};}
export async function actorFrom(db:Database,row:Row):Promise<Actor>{const role=await one(db,'SELECT * FROM roles WHERE id=?',String(row.role_id));ensure(role&&row.active===1,'Access is disabled.',403);return{id:String(row.id),name:String(row.name),role:String(role.name),permissions:parse<string[]>(role.permissions_json,[]),locationId:String(row.location_id),sessionId:'',terminalId:null,platformId:row.platform_id?String(row.platform_id):null};}
export async function session(db:Database,req:Request,allowLocked=false){const t=cookies(req).dawat_session;ensure(t,'Sign in to continue.',401,'AUTH');const sess=await one(db,'SELECT * FROM sessions WHERE id=?',await hash(t));ensure(sess&&String(sess.expires_at)>now(),'Your session expired. Sign in again.',401,'AUTH');const row=await one(db,'SELECT * FROM staff WHERE id=?',String(sess.staff_id));ensure(row,'Sign in to continue.',401,'AUTH');const actor=await actorFrom(db,row);actor.sessionId=String(sess.id);actor.terminalId=sess.terminal_id?String(sess.terminal_id):null;const {settings}=await settingsFor(db,actor.locationId);ensure(Date.parse(String(sess.last_seen_at))+settings.sessionMinutes*60e3>Date.now(),'Your session expired. Sign in again.',401,'AUTH');if(sess.platform_id)ensure(req.headers.get('oai-authenticated-user-id')===sess.platform_id,'Sign in with your authorized workspace account.',401,'AUTH');ensure(allowLocked||!sess.locked,'Unlock this terminal to continue.',423,'LOCKED');if(req.method!=='GET'){ensure(await hash(req.headers.get('x-csrf-token')||'')===sess.csrf_hash,'Reload the application before trying again.',403,'CSRF');await s(db,'UPDATE sessions SET last_seen_at=? WHERE id=?',now(),actor.sessionId).run();}return{actor,settings,locked:!!sess.locked};}
export async function newSession(db:Database,req:Request,row:Row,terminalId:string|null=null){const a=await actorFrom(db,row),raw=token(),csrf=token(),id=await hash(raw);a.sessionId=id;a.terminalId=terminalId;await atomic(db,[insert(db,'sessions',{id,staff_id:a.id,terminal_id:terminalId,platform_id:req.headers.get('oai-authenticated-user-id'),csrf_hash:await hash(csrf),created_at:now(),last_seen_at:now(),expires_at:new Date(Date.now()+12*3600e3).toISOString(),locked:0}),audit(db,a,'Login','staff',a.id)]);return{actor:a,csrf,cookies:[cookie(req,'dawat_session',raw),cookie(req,'dawat_csrf',csrf,false)]};}
export async function platformLogin(db:Database,req:Request){const platform=req.headers.get('oai-authenticated-user-id'),email=req.headers.get('oai-authenticated-user-email');ensure(platform&&email,'Open the private application with your authorized ChatGPT account.',401);let row=await one(db,'SELECT * FROM staff WHERE platform_id=?',platform);if(!row){const existing=await one(db,'SELECT id FROM restaurants LIMIT 1');ensure(!existing,'Your workspace identity is not assigned to a staff account. Use your staff credentials.',403);const location=uid(),restaurant=uid(),staff=uid(),stamp=now();let name=email;const fullname=req.headers.get('oai-authenticated-user-full-name');if(fullname&&req.headers.get('oai-authenticated-user-full-name-encoding')==='percent-encoded-utf-8'){try{name=decodeURIComponent(fullname);}catch{/* Fall back to the verified email. */}}
 const statements:Stmt[]=[insert(db,'restaurants',{id:restaurant,name:defaults.restaurantName,created_at:stamp}),insert(db,'locations',{id:location,restaurant_id:restaurant,name:'Tanuku',created_at:stamp}),insert(db,'settings',{id:uid(),location_id:location,data_json:json(defaults),version:1,updated_at:stamp})];for(const [role,perms] of Object.entries(roles))statements.push(insert(db,'roles',{id:role,name:role,permissions_json:json(perms),system:1,version:1}));row={id:staff,location_id:location,name,email:email.toLowerCase(),code:'OWNER',role_id:'Owner',platform_id:platform,active:1,version:1,created_at:stamp};statements.push(insert(db,'staff',row));const cats=[...new Set(seed.map(i=>i.category))];cats.forEach((category,i)=>statements.push(insert(db,'categories',{id:category,location_id:location,name:category.split('-').map(s=>s[0].toUpperCase()+s.slice(1)).join(' '),sort:i,active:1,version:1})));seed.forEach((m,i)=>statements.push(insert(db,'menu_items',{id:m.id,location_id:location,name:m.name,category_id:m.category,subcategory:m.subcategory,diet:m.diet,price_paise:m.pricePaise,signature:m.signature?1:0,channels_json:json(defaults.orderTypes),sort:i,created_at:stamp})));for(const [id,name,dimension,factor] of [['g','Gram','mass',1],['kg','Kilogram','mass',1000],['ml','Millilitre','volume',1],['l','Litre','volume',1000],['each','Each','count',1]] as const)statements.push(insert(db,'units',{id,name,dimension,factor}));await atomic(db,statements);}
 return newSession(db,req,row);
}
export async function login(db:Database,req:Request,p:Input){const login=str(p.login,254,true).toLowerCase(),secret=str(p.secret,128,true);await rateLimit(db,'login:'+login);await rateLimit(db,'device:'+(req.headers.get('cf-connecting-ip')||cookies(req).dawat_device||'unpaired'),30);let row:Row|null,terminal:Row|null=null;if(p.mode==='pin'){const device=cookies(req).dawat_device;ensure(device,'A manager must pair this terminal before staff PIN access.',403);terminal=await one(db,'SELECT * FROM terminals WHERE device_hash=? AND active=1',await hash(device));ensure(terminal,'Terminal pairing expired. Ask a manager to pair it again.',403);row=await one(db,'SELECT * FROM staff WHERE lower(code)=? AND location_id=? AND active=1',login,String(terminal.location_id));ensure(row&&await verify(secret,row.pin_hash),'Staff code or PIN is incorrect.',401);}else{row=await one(db,'SELECT * FROM staff WHERE lower(email)=? AND active=1',login);ensure(row&&await verify(secret,row.password_hash),'Email or password is incorrect.',401);}return newSession(db,req,row,terminal?String(terminal.id):null);}
export async function authorizeSensitive(c:Context,action:string,entity:string,p:Input):Promise<{approver:string;statements:Stmt[]}>{if(c.actor.permissions.includes(action)&&(['Owner','Admin','Manager'].includes(c.actor.role)||(action==='bill.refund'&&!c.settings.requireRefundApproval)||(action==='cash.adjust'&&!c.settings.requireCashApproval)))return{approver:c.actor.id,statements:[]};ensure(p.approvalId,'Manager approval is required for this action.',403,'APPROVAL_REQUIRED');const id=str(p.approvalId,100,true),r=await one(c.db,'SELECT * FROM approvals WHERE id=?',id);const clean={...p};delete clean.approvalId;ensure(r&&r.actor_id===c.actor.id&&r.action===action&&r.entity_id===entity&&!r.used_at&&String(r.expires_at)>now()&&r.request_hash===await hash(canonical(clean)),'Manager approval is required for this exact action.',403,'APPROVAL_REQUIRED');return{approver:String(r.approver_id),statements:[s(c.db,'UPDATE approvals SET used_at=? WHERE id=? AND used_at IS NULL',now(),id),...guard(c.db,'changes()=1')]};}
export async function approve(c:Context,p:Input){const code=str(p.code,32,true).toLowerCase();await rateLimit(c.db,'approval:'+code,5);const manager=await one(c.db,'SELECT * FROM staff WHERE lower(code)=? AND location_id=? AND active=1',code,c.actor.locationId);ensure(manager&&await verify(str(p.pin,10,true),manager.pin_hash),'Manager code or PIN is incorrect.',403);const a=await actorFrom(c.db,manager),action=str(p.action,80,true);ensure(['Owner','Admin','Manager'].includes(a.role),'Manager authorization is required.',403);permit(a,action);ensure(['order.void','order.cancel','order.discount.manual','bill.refund','bill.cancel','cash.adjust'].includes(action),'This action does not accept a PIN approval.');const id=uid(),entity=str(p.entityId,100,true);await atomic(c.db,[insert(c.db,'approvals',{id,location_id:c.actor.locationId,actor_id:c.actor.id,approver_id:a.id,action,entity_id:entity,request_hash:await hash(canonical(p.request)),expires_at:new Date(Date.now()+120000).toISOString()}),audit(c.db,a,'Manager approval',action,entity,null,{actor:c.actor.id})]);return{id};}
export async function pair(c:Context,req:Request,p:Input){permit(c.actor,'settings.manage');const id=str(p.terminalId,100,true),t=await one(c.db,'SELECT * FROM terminals WHERE id=? AND location_id=? AND active=1',id,c.actor.locationId);ensure(t,'Choose an active terminal.');const device=token();await atomic(c.db,[s(c.db,'UPDATE terminals SET device_hash=?,version=version+1 WHERE id=?',await hash(device),id),s(c.db,'UPDATE sessions SET terminal_id=? WHERE id=?',id,c.actor.sessionId),audit(c.db,c.actor,'Terminal paired','terminals',id)]);return{cookies:[cookie(req,'dawat_device',device,true,90*86400)],terminalId:id};}
export function validatePassword(value:unknown){const v=str(value,128,true);ensure(v.length>=12,'Use at least 12 characters for passwords.');return v;}
export function validatePin(value:unknown,length:number){const v=str(value,10,true);ensure(new RegExp(`^\\d{${int(length,6,10)}}$`).test(v)&&!/^([0-9])\1+$/.test(v)&&!('01234567890123456789'.includes(v)||'98765432109876543210'.includes(v)),'Use a non-repeating PIN of the configured length.');return v;}
export async function safeRoles(db:Database){return all(db,'SELECT id,name,permissions_json,system,version FROM roles');}
export const knownPermissions=permissions;
