import {operationalNotifications} from './notifications';
import {can,ensure,int,permit} from '../domain';
import {resources} from '../catalog';
import {all,Context,one,owned,Row} from './db';
import {settingsFor} from './auth';
import {activeShift,shiftSummary} from './finance';
import {menuAvailable} from './orders';
import {loyaltyBalance} from './loyalty';
import {purchaseDetail} from './stock';
export async function bootstrap(c:Context){const {settings,version}=await settingsFor(c.db,c.actor.locationId),loc=c.actor.locationId;const menu=can(c.actor,'menu.view')?await all(c.db,'SELECT * FROM menu_items WHERE location_id=? ORDER BY sort,name',loc):[];const catalog:Record<string,Row[]>={};for(const kind of ['categories','sections','tables','stations','terminals','taxes','printers','modifier-groups'])catalog[kind]=await all(c.db,`SELECT ${kind==='terminals'?'id,name,type,active,version':'*'} FROM ${resources[kind].table} WHERE location_id=? ORDER BY name`,loc);catalog.units=await all(c.db,'SELECT * FROM units');catalog.modifiers=await all(c.db,'SELECT m.* FROM modifiers m JOIN modifier_groups g ON g.id=m.group_id WHERE g.location_id=?',loc);catalog.staff=await all(c.db,'SELECT s.id,s.name,s.code,s.role_id,s.active,s.version,r.name role_name FROM staff s JOIN roles r ON r.id=s.role_id WHERE s.location_id=?',loc);catalog.bindings=await all(c.db,'SELECT m.* FROM menu_item_modifiers m JOIN menu_items i ON i.id=m.menu_item_id WHERE i.location_id=?',loc);catalog.assignments=await all(c.db,'SELECT a.* FROM table_assignments a JOIN orders o ON o.id=a.order_id WHERE o.location_id=?',loc);if(can(c.actor,'staff.manage'))catalog.roles=await all(c.db,'SELECT * FROM roles');const setupIssues:string[]=[];if(!settings.legalName)setupIssues.push('Confirm the legal business name.');if(!settings.invoicePrefix)setupIssues.push('Set an invoice prefix.');if(!settings.taxConfigured&&!settings.noTaxConfirmed)setupIssues.push('Confirm tax treatment.');if(!catalog.terminals.some(x=>x.active))setupIssues.push('Add and pair a terminal.');if(!settings.liveBillingEnabled)setupIssues.push('Live billing is disabled until setup is complete.');const shift=await activeShift(c);return{actor:c.actor,settings,settingsVersion:version,menu:menu.map(m=>({...m,current_available:menuAvailable(m,settings.timezone)?1:0})),catalog,activeShift:shift?await shiftSummary(c,String(shift.id)):null,setupIssues};}
export async function recordList(c:Context,kind:string,q:string,page:number,history=false){int(page,1,100000);let sql='',countSql='',values:(string|number|null)[]=[];const loc=c.actor.locationId,like='%'+q+'%';if(kind==='orders'){ensure(can(c.actor,'order.create')||can(c.actor,'order.completed.view')||can(c.actor,'kitchen.view'),'Your role cannot view orders.',403);if(history)permit(c.actor,'order.completed.view');const filter=history?'':"AND o.status NOT IN ('Closed','Cancelled','Merged','Refunded')";sql=`SELECT o.*,c.name customer_name,i.number invoice_number,(SELECT GROUP_CONCAT(t.name,', ') FROM table_assignments a JOIN dining_tables t ON t.id=a.table_id WHERE a.order_id=o.id) table_names FROM orders o LEFT JOIN customers c ON c.id=o.customer_id LEFT JOIN invoices i ON i.order_id=o.id WHERE o.location_id=? ${filter} AND (o.number LIKE ? OR COALESCE(i.number,'') LIKE ? OR COALESCE(c.phone,'') LIKE ? OR COALESCE(c.name,'') LIKE ?) ORDER BY o.created_at DESC`;values=[loc,like,like,like,like];}
 else if(kind==='kitchen'){permit(c.actor,'kitchen.view');sql=`SELECT k.*,o.number order_number,o.type,o.status order_status,(SELECT GROUP_CONCAT(t.name,', ') FROM table_assignments a JOIN dining_tables t ON t.id=a.table_id WHERE a.order_id=o.id) table_names,st.name station_name FROM kots k JOIN orders o ON o.id=k.order_id LEFT JOIN stations st ON st.id=k.station_id WHERE k.location_id=? ${history?'':"AND k.status<>'Completed'"} ORDER BY k.created_at`;values=[loc];}
 else if(kind==='audit'){permit(c.actor,'audit.view');sql='SELECT * FROM audit_logs WHERE location_id=? AND (action LIKE ? OR actor_name LIKE ? OR entity_id LIKE ?) ORDER BY created_at DESC';values=[loc,like,like,like];}
 else if(kind==='staff'){permit(c.actor,'staff.manage');sql='SELECT s.id,s.name,s.email,s.code,s.role_id,s.active,s.version,s.created_at,r.name role_name FROM staff s JOIN roles r ON r.id=s.role_id WHERE s.location_id=? AND (s.name LIKE ? OR s.code LIKE ?) ORDER BY s.name';values=[loc,like,like];}
 else if(kind==='purchases'){permit(c.actor,'purchase.create');sql='SELECT p.*,s.name supplier_name FROM purchases p JOIN suppliers s ON s.id=p.supplier_id WHERE p.location_id=? AND (p.number LIKE ? OR s.name LIKE ?) ORDER BY p.created_at DESC';values=[loc,like,like];}
 else if(kind==='shifts'){permit(c.actor,'shift.open');sql='SELECT sh.*,t.name terminal_name,s.name staff_name FROM shifts sh JOIN terminals t ON t.id=sh.terminal_id JOIN staff s ON s.id=sh.staff_id WHERE sh.location_id=? ORDER BY sh.opened_at DESC';values=[loc];}
 else if(kind==='recipes'){permit(c.actor,'inventory.view');sql='SELECT r.*,m.name FROM recipes r JOIN menu_items m ON m.id=r.menu_item_id WHERE m.location_id=? AND m.name LIKE ? ORDER BY m.name';values=[loc,like];}
 else if(kind==='stock-counts'){permit(c.actor,'inventory.view');sql='SELECT * FROM stock_counts WHERE location_id=? ORDER BY created_at DESC';values=[loc];}
 else if(kind==='ledger'||kind==='wastage'){permit(c.actor,'inventory.view');sql=`SELECT m.*,i.name,u.name unit_name FROM ${kind==='ledger'?'stock_movements':'wastage'} m JOIN inventory_items i ON i.id=m.inventory_item_id JOIN units u ON u.id=i.unit_id WHERE m.location_id=? AND i.name LIKE ? ORDER BY m.created_at DESC`;values=[loc,like];}
 else if(kind==='expenses'){permit(c.actor,'expense.manage');sql='SELECT e.*,s.name authorized_by_name FROM expenses e JOIN staff s ON s.id=e.authorized_by WHERE e.location_id=? AND (e.category LIKE ? OR e.description LIKE ?) ORDER BY e.date DESC';values=[loc,like,like];}
 else if(kind==='notifications')return operationalNotifications(c);
 else{const resource=resources[kind];ensure(resource,'Unknown record type.',404);permit(c.actor,kind==='menu'?'menu.view':kind==='inventory'?'inventory.view':resource.permission);if(kind==='modifiers'){sql='SELECT m.* FROM modifiers m JOIN modifier_groups g ON g.id=m.group_id WHERE g.location_id=? AND m.name LIKE ? ORDER BY m.name';values=[loc,like];}else if(kind==='customers'||kind==='suppliers'){sql=`SELECT * FROM ${resource.table} WHERE location_id=? AND (name LIKE ? OR phone LIKE ?) ORDER BY name`;values=[loc,like,like];}else if(kind==='inventory'){sql='SELECT i.*,u.name unit_name FROM inventory_items i JOIN units u ON u.id=i.unit_id WHERE i.location_id=? AND i.name LIKE ? ORDER BY i.name';values=[loc,like];}else{sql=`SELECT ${kind==='terminals'?'id,location_id,name,type,active,version,created_at':'*'} FROM ${resource.table} WHERE location_id=? AND ${kind==='coupons'?'code':'name'} LIKE ? ORDER BY ${kind==='coupons'?'code':'name'}`;values=[loc,like];}}
 countSql='SELECT COUNT(*) total FROM ('+sql+')';const count=await one(c.db,countSql,...values);const rows=await all(c.db,sql+' LIMIT 100 OFFSET ?',...values,(page-1)*100);if(kind==='kitchen'){const enriched=[];for(const row of rows)enriched.push({...row,items:await all(c.db,'SELECT ki.*,oi.voided,oi.void_reason FROM kot_items ki JOIN order_items oi ON oi.id=ki.order_item_id WHERE ki.kot_id=?',String(row.id))});return{rows:enriched,total:Number(count?.total),page,pageSize:100};}return{rows,total:Number(count?.total),page,pageSize:100};}
export async function detail(c:Context,kind:string,id:string){if(kind==='purchases'){permit(c.actor,'purchase.create');return purchaseDetail(c,id);}if(kind==='customers'){permit(c.actor,'customer.manage');const customer=await owned(c.db,c.actor,'customers',id),orders=await all(c.db,'SELECT o.id,o.number,o.type,o.status,o.created_at,i.number invoice_number,i.total_paise FROM orders o LEFT JOIN invoices i ON i.order_id=o.id WHERE o.customer_id=? ORDER BY o.created_at DESC LIMIT 100',id),stats=await one(c.db,"SELECT COUNT(*) visits,COALESCE(SUM(i.total_paise),0) spend_paise,MAX(i.finalized_at) last_visit FROM invoices i JOIN orders o ON o.id=i.order_id WHERE o.customer_id=? AND NOT EXISTS (SELECT 1 FROM invoice_events e WHERE e.invoice_id=i.id AND e.action='Cancelled')",id);return{customer,orders,stats,loyalty:await loyaltyBalance(c,id)};}if(kind==='recipes'){permit(c.actor,'inventory.view');const recipe=await one(c.db,'SELECT r.* FROM recipes r JOIN menu_items m ON m.id=r.menu_item_id WHERE r.id=? AND m.location_id=?',id,c.actor.locationId);ensure(recipe,'Recipe not found.',404);return{recipe,items:await all(c.db,'SELECT ri.*,i.name,u.name unit_name FROM recipe_items ri JOIN inventory_items i ON i.id=ri.inventory_item_id JOIN units u ON u.id=i.unit_id WHERE ri.recipe_id=?',id)};}if(kind==='stock-counts'){permit(c.actor,'inventory.view');return{count:await owned(c.db,c.actor,'stock_counts',id),items:await all(c.db,'SELECT ci.*,i.name,u.name unit_name FROM stock_count_items ci JOIN inventory_items i ON i.id=ci.inventory_item_id JOIN units u ON u.id=i.unit_id WHERE ci.count_id=?',id)};}ensure(false,'Unknown detail page.',404);}
export async function search(c:Context,q:string){ensure(q.length>=2&&q.length<=100,'Enter 2–100 characters.');const results:Row[]=[];for(const [kind,permission] of [['orders','order.create'],['menu','menu.view'],['customers','customer.manage'],['suppliers','supplier.manage'],['purchases','purchase.create'],['staff','staff.manage']]){if(can(c.actor,permission)){const result=await recordList(c,kind,q,1,kind==='orders'&&can(c.actor,'order.completed.view'));for(const r of result.rows.slice(0,8)){const row=r as Row;results.push({id:row.id,kind,label:row.name||row.number||row.code,detail:row.status||row.type||row.phone||''});};}}return{results};}
