'use client';
import {FormEvent,ReactNode,useState} from 'react';
import {AlertCircle,ChevronLeft,ChevronRight,LoaderCircle,PackageOpen,RefreshCw} from 'lucide-react';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Label} from '@/components/ui/label';import {Textarea} from '@/components/ui/textarea';import {Switch} from '@/components/ui/switch';import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle} from '@/components/ui/alert-dialog';import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';import {Empty,EmptyDescription,EmptyHeader,EmptyMedia,EmptyTitle} from '@/components/ui/empty';import {Skeleton} from '@/components/ui/skeleton';import {Pagination,PaginationContent,PaginationItem} from '@/components/ui/pagination';
import {api,ApiError,Data,dateTime,money,num,txt} from '@/lib/client';
export function Choice({value,onChange,options,label,disabled=false}:{value:string;onChange:(x:string)=>void;options:(string|{value:string;label:string})[];label?:string;disabled?:boolean}){return <Select value={value||'__none'} onValueChange={v=>onChange(v==='__none'?'':v)} disabled={disabled}><SelectTrigger className="h-11 w-full" aria-label={label||'Choose option'}><SelectValue placeholder="Choose…"/></SelectTrigger><SelectContent>{options.map(o=>{const item=typeof o==='string'?{value:o,label:o}:o;return <SelectItem key={item.value||'__none'} value={item.value||'__none'}>{item.label}</SelectItem>;})}</SelectContent></Select>;}
export type FormField={name:string;label:string;type?:string;required?:boolean;options?:(string|{value:string;label:string})[];help?:string;min?:number;step?:string;default?:unknown};
export function Form({fields,initial={},submit='Save',onSubmit,children}:{fields:FormField[];initial?:Data;submit?:string;onSubmit:(p:Data)=>Promise<unknown>;children?:ReactNode}){const [values,setValues]=useState<Data>(()=>Object.fromEntries(fields.map(f=>[f.name,initial[f.name]??f.default??(f.type==='boolean'?false:'')]))),[busy,setBusy]=useState(false),[error,setError]=useState('');const change=(name:string,value:unknown)=>setValues(v=>({...v,[name]:value}));async function send(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{await onSubmit(values);}catch(e){setError(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}}return <form onSubmit={send} className="os-form"><div className="form-fields">{fields.map(f=><div className={'field '+(f.type==='textarea'?'wide':'')} key={f.name}><Label htmlFor={'field-'+f.name}>{f.label}{f.required&&<span aria-hidden="true"> *</span>}</Label>{f.type==='boolean'?<Switch id={'field-'+f.name} checked={!!values[f.name]} onCheckedChange={v=>change(f.name,v)} aria-label={f.label}/>:f.options?<Choice label={f.label} value={txt(values[f.name])} onChange={v=>change(f.name,v)} options={f.options}/>:f.type==='textarea'?<Textarea id={'field-'+f.name} value={txt(values[f.name])} onChange={e=>change(f.name,e.target.value)} required={f.required} rows={3}/>:<Input id={'field-'+f.name} className="h-11" type={f.type||'text'} value={txt(values[f.name])} onChange={e=>change(f.name,e.target.value)} required={f.required} min={f.min} step={f.step} autoComplete={f.type==='password'?'new-password':'off'}/>} {f.help&&<p className="muted text-sm">{f.help}</p>}</div>)}</div>{children}{error&&<div role="alert" className="error-note"><AlertCircle size={18}/>{error}</div>}<Button type="submit" className="h-11" disabled={busy}>{busy&&<LoaderCircle className="animate-spin" size={17}/>} {busy?'Saving…':submit}</Button></form>;}
export function Modal({title,description,children,onClose,wide=false}:{title:string;description?:string;children:ReactNode;onClose:()=>void;wide?:boolean}){return <Dialog open onOpenChange={open=>{if(!open)onClose();}}><DialogContent className={'os-dialog '+(wide?'sm:max-w-3xl':'sm:max-w-xl')}><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description||'Review the details below.'}</DialogDescription></DialogHeader>{children}</DialogContent></Dialog>;}
export function Confirm({title,description,onConfirm,onClose}:{title:string;description:string;onConfirm:()=>Promise<unknown>;onClose:()=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState('');return <AlertDialog open onOpenChange={v=>{if(!v)onClose();}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{title}</AlertDialogTitle><AlertDialogDescription>{description}</AlertDialogDescription></AlertDialogHeader>{error&&<p role="alert" className="error-note">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Keep record</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();setBusy(true);try{await onConfirm();onClose();}catch(err){setError(err instanceof Error?err.message:'Unable to complete.');}finally{setBusy(false);}}}>{busy?'Working…':'Confirm'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>;}
export function Status({value}:{value:unknown}){const label=txt(value);const tone=['Paid','Ready','Available','Received','Completed','Confirmed','Online'].includes(label)?'good':['Cancelled','Refunded','Sold out','Reversed','Conflict'].includes(label)?'bad':['New','Open','Preparing','Part paid','Cleaning','Bill requested','Draft'].includes(label)?'warm':'neutral';return <span className={'status '+tone}>{label||'—'}</span>;}
export function EmptyState({title='No records yet',text='Records will appear here when you add them.',action}:{title?:string;text?:string;action?:ReactNode}){return <Empty className="empty-state"><EmptyHeader><EmptyMedia variant="icon"><PackageOpen/></EmptyMedia><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{text}</EmptyDescription></EmptyHeader>{action}</Empty>;}
export function ErrorState({message,retry}:{message:string;retry?:()=>void}){return <div role="alert" className="error-note"><AlertCircle size={20}/><span>{message}</span>{retry&&<Button variant="outline" onClick={retry}><RefreshCw size={16}/> Retry</Button>}</div>;}
export function Loading(){return <div className="loading-panel" aria-label="Loading records"><Skeleton className="h-8 w-52"/><Skeleton className="h-24 w-full"/><Skeleton className="h-24 w-full"/></div>;}
export function valueLabel(key:string){return key.replaceAll('_',' ').replace(/paise$/,'(₹)').replace(/milli$/,'(units)').replace(/^./,c=>c.toUpperCase());}
export function cellValue(value:unknown,key:string):ReactNode{if(value===null||value===undefined||value==='')return <span className="muted">—</span>;if(key.endsWith('_paise'))return <span className="numeric">{money(value)}</span>;if(key.endsWith('_milli'))return <span className="numeric">{(num(value)/1000).toLocaleString('en-IN',{maximumFractionDigits:3})}</span>;if(key.endsWith('_at'))return <span className="text-sm">{dateTime(value)}</span>;if(key==='status')return <Status value={value}/>;if(typeof value==='object')return JSON.stringify(value);return txt(value);}
export function RecordsTable({rows,columns,onOpen,actions}:{rows:Data[];columns?:string[];onOpen?:(row:Data)=>void;actions?:(row:Data)=>ReactNode}){if(!rows.length)return <EmptyState/>;const cols=columns||Object.keys(rows[0]);return <div className="table-surface"><Table><TableHeader><TableRow>{cols.map(k=><TableHead key={k}>{valueLabel(k)}</TableHead>)}{actions&&<TableHead>Actions</TableHead>}</TableRow></TableHeader><TableBody>{rows.map((r,i)=><TableRow key={txt(r.id)||i}>{cols.map((k,j)=><TableCell key={k}>{j===0&&onOpen?<button type="button" className="row-link" onClick={()=>onOpen(r)}>{cellValue(r[k],k)}</button>:cellValue(r[k],k)}</TableCell>)}{actions&&<TableCell>{actions(r)}</TableCell>}</TableRow>)}</TableBody></Table></div>;}
export function Pager({page,total,onChange}:{page:number;total:number;onChange:(n:number)=>void}){return <Pagination className="justify-end mt-4"><PaginationContent><PaginationItem><span className="text-sm muted mr-3">{total} records · Page {page} of {Math.max(1,Math.ceil(total/100))}</span></PaginationItem><PaginationItem><Button variant="outline" size="icon" disabled={page<=1} onClick={()=>onChange(page-1)} aria-label="Previous page"><ChevronLeft/></Button></PaginationItem><PaginationItem><Button variant="outline" size="icon" disabled={page*100>=total} onClick={()=>onChange(page+1)} aria-label="Next page"><ChevronRight/></Button></PaginationItem></PaginationContent></Pagination>;}
export function useAuthorized(){const [approval,setApproval]=useState<{path:string;payload:Data;action:string;entityId:string;resolve:(x:Data)=>void;reject:(e:Error)=>void}|null>(null);async function execute(path:string,payload:Data,action?:string,entityId?:string):Promise<Data>{try{return await api(path,payload);}catch(e){if(e instanceof ApiError&&e.code==='APPROVAL_REQUIRED'&&action&&entityId)return new Promise((resolve,reject)=>setApproval({path,payload,action,entityId,resolve,reject}));throw e;}}const dialog=approval?<Modal title="Manager authorization" description="A manager must approve this exact action using their staff code and PIN." onClose={()=>{approval.reject(new Error('Manager approval was cancelled.'));setApproval(null);}}><Form fields={[{name:'code',label:'Manager staff code',required:true},{name:'pin',label:'Manager PIN',type:'password',required:true}]} submit="Authorize action" onSubmit={async values=>{const result=await api('auth/approve',{...values,action:approval.action,entityId:approval.entityId,request:approval.payload});const response=await api(approval.path,{...approval.payload,approvalId:result.id});approval.resolve(response);setApproval(null);}}/></Modal>:null;return{execute,dialog};}
