export type Field={label:string;type?:'text'|'number'|'money'|'quantity'|'boolean'|'choice'|'date'|'textarea'|'json';required?:boolean;options?:string[];ref?:string;nullable?:boolean;default?:string|number;help?:string};
export type Resource={table:string;label:string;singular:string;permission:string;fields:Record<string,Field>;created?:boolean;global?:boolean};
const name:Field={label:'Name',required:true},notes:Field={label:'Notes',type:'textarea'},active:Field={label:'Active',type:'boolean',default:1};
export const resources:Record<string,Resource>={
 categories:{table:'categories',label:'Categories',singular:'Category',permission:'menu.edit',fields:{name,sort:{label:'Display order',type:'number',default:0},active}},
 sections:{table:'table_sections',label:'Dining sections',singular:'Dining section',permission:'settings.manage',fields:{name,sort:{label:'Display order',type:'number',default:0},active}},
 tables:{table:'dining_tables',label:'Tables',singular:'Table',permission:'settings.manage',fields:{name,section_id:{label:'Section',ref:'sections',nullable:true},capacity:{label:'Seats',type:'number',required:true},sort:{label:'Display order',type:'number',default:0},active}},
 stations:{table:'stations',label:'Kitchen stations',singular:'Kitchen station',permission:'settings.manage',fields:{name,printer_id:{label:'Printer',ref:'printers',nullable:true},overdue_minutes:{label:'Overdue after (minutes)',type:'number',nullable:true},active}},
 terminals:{table:'terminals',label:'Terminals',singular:'Terminal',permission:'settings.manage',created:true,fields:{name,type:{label:'Terminal type',type:'choice',options:['POS','Manager','Kitchen','Waiter'],default:'POS'},active}},
 taxes:{table:'tax_profiles',label:'Tax profiles',singular:'Tax profile',permission:'settings.manage',fields:{name,components_json:{label:'Tax components',type:'json',required:true,help:'An array of {"name":"…","rateBps":…}. Enter only tax rates confirmed for your business; 100 basis points = 1%.'},inclusive:{label:'Prices include this tax',type:'boolean',default:0},active}},
 menu:{table:'menu_items',label:'Menu items',singular:'Menu item',permission:'menu.edit',created:true,fields:{name,display_name:{label:'Receipt name',nullable:true},category_id:{label:'Category',ref:'categories',required:true},subcategory:{label:'Subcategory',nullable:true},sku:{label:'SKU',nullable:true},diet:{label:'Dietary marker',type:'choice',options:['veg','non-veg','unspecified'],default:'unspecified'},price_paise:{label:'Selling price (₹)',type:'money',nullable:true},tax_profile_id:{label:'Tax profile',ref:'taxes',nullable:true},station_id:{label:'Kitchen station',ref:'stations',nullable:true},prep_minutes:{label:'Preparation time (minutes)',type:'number',nullable:true},channels_json:{label:'Allowed order types',type:'json',default:'["Dine-in","Takeaway","Delivery","Online"]',help:'Dine-in, Takeaway, Delivery, Online'},description:{label:'Description',type:'textarea',nullable:true},signature:{label:'Signature dish',type:'boolean',default:0},active}},
 inventory:{table:'inventory_items',label:'Stock items',singular:'Stock item',permission:'inventory.manage',created:true,fields:{name,type:{label:'Stock type',type:'choice',options:['Raw ingredient','Finished item','Packaging'],required:true},unit_id:{label:'Stock unit',ref:'units',required:true},minimum_milli:{label:'Low stock threshold',type:'quantity',nullable:true},reorder_milli:{label:'Reorder quantity',type:'quantity',nullable:true},active}},
 suppliers:{table:'suppliers',label:'Suppliers',singular:'Supplier',permission:'supplier.manage',created:true,fields:{name,contact:{label:'Contact person',nullable:true},phone:{label:'Phone',nullable:true},email:{label:'Email',nullable:true},gstin:{label:'GSTIN (if applicable)',nullable:true},address:{label:'Address',type:'textarea',nullable:true},products:{label:'Products supplied',nullable:true},notes,active}},
 customers:{table:'customers',label:'Customers',singular:'Customer',permission:'customer.manage',created:true,fields:{name,phone:{label:'Phone (optional)',nullable:true},email:{label:'Email (optional)',nullable:true},birthday:{label:'Birthday (voluntary)',type:'date',nullable:true},anniversary:{label:'Anniversary (voluntary)',type:'date',nullable:true},notes,active}},
 printers:{table:'printers',label:'Printers',singular:'Printer',permission:'settings.manage',fields:{name,type:{label:'Printer purpose',type:'choice',options:['Billing','Kitchen','Beverage','Biryani','Main Kitchen'],required:true},width:{label:'Paper size',type:'choice',options:['58','80','A4'],default:'80'},copies:{label:'Copies',type:'number',default:1},active}},
 'modifier-groups':{table:'modifier_groups',label:'Modifier groups',singular:'Modifier group',permission:'menu.edit',fields:{name,required:{label:'Selection required',type:'boolean',default:0},multiple:{label:'Allow multiple options',type:'boolean',default:0},min:{label:'Minimum selections',type:'number',default:0},max:{label:'Maximum selections',type:'number',default:1},active}},
 modifiers:{table:'modifiers',label:'Modifier options',singular:'Modifier option',permission:'menu.edit',global:true,fields:{group_id:{label:'Modifier group',ref:'modifier-groups',required:true},name,price_paise:{label:'Additional price (₹)',type:'money',default:0},active}},
 coupons:{table:'coupons',label:'Coupons',singular:'Coupon',permission:'settings.manage',fields:{code:{label:'Coupon code',required:true},type:{label:'Discount type',type:'choice',options:['fixed','percent'],required:true},value:{label:'Value (paise or basis points)',type:'number',required:true,help:'100 paise = ₹1; 100 basis points = 1%.'},starts_at:{label:'Starts at (ISO date/time)',nullable:true},ends_at:{label:'Ends at (ISO date/time)',nullable:true},min_paise:{label:'Minimum order (₹)',type:'money',default:0},active}}
};
