export class Problem extends Error { constructor(public status:number,message:string,public code='INVALID'){super(message);} }
export function ensure(ok:unknown,message:string,status=400,code='INVALID'):asserts ok {if(!ok)throw new Problem(status,message,code);}
export function int(x:unknown,min=0,max=100_000_000){ensure(typeof x==='number'&&Number.isSafeInteger(x)&&x>=min&&x<=max,'Enter a valid whole number.');return x;}
export function str(x:unknown,max=500,required=false){ensure(typeof x==='string'&&x.length<=max&&(!required||x.trim().length),'Enter valid text.');return x.trim();}
export function paise(x:string){ensure(/^\d+(\.\d{1,2})?$/.test(x),'Use a positive amount with up to two decimals.');return int(Math.round(Number(x)*100));}
export function allocate(total:number,weights:number[]){int(total);ensure(weights.length>0&&weights.every(x=>x>=0&&Number.isFinite(x)),'Invalid allocation.');const sum=weights.reduce((a,b)=>a+b,0);ensure(sum>0||total===0,'No amount to allocate.');if(!sum)return weights.map(()=>0);const parts=weights.map((w,i)=>({i,n:Math.floor(total*w/sum),r:total*w/sum%1}));let remaining=total-parts.reduce((a,p)=>a+p.n,0);for(const p of [...parts].sort((a,b)=>b.r-a.r||a.i-b.i)){if(remaining-->0)p.n++;}return parts.map(p=>p.n);}
export type Tax={id:string;name:string;inclusive:boolean;components:{name:string;rateBps:number}[]};
export type Line={id:string;menuItemId:string;name:string;category:string;quantity:number;unitPaise:number;modifierPaise:number;modifiers:{id:string;name:string;pricePaise:number}[];note:string;seat:string;discountPaise:number;tax:Tax|null};
export type Settings={restaurantName:string;legalName:string;address:string;phone:string;email:string;gstin:string;state:string;placeOfSupply:string;hsnSac:string;timezone:string;currency:string;invoicePrefix:string;invoiceDigits:number;receiptFooter:string;receiptWidth:string;taxConfigured:boolean;noTaxConfirmed:boolean;defaultTaxProfileId:string|null;roundOff:boolean;packingPaise:number;deliveryPaise:number;serviceChargeBps:number;chargeTaxProfileId:string|null;tipsEnabled:boolean;orderTypes:string[];defaultOrderType:string;paymentMethods:string[];upiId:string;upiName:string;manualDiscountsEnabled:boolean;discountLimitBps:number|null;requireVoidApproval:boolean;requireRefundApproval:boolean;requireCashApproval:boolean;autoDeduct:boolean;allowNegativeStock:boolean;lowStockAlerts:boolean;loyaltyEnabled:boolean;loyaltyEarnPaise:number|null;loyaltyEarnPoints:number|null;loyaltyFixedPoints:number|null;loyaltyRedeemPaise:number|null;loyaltyMinPoints:number|null;loyaltyExpiryDays:number|null;sessionMinutes:number;pinLength:number;notificationOverdueMinutes:number|null;requireShift:boolean;liveBillingEnabled:boolean};
export const defaults:Settings={restaurantName:'Dawat Family Restaurant',legalName:'',address:'Ward-19, Rajiv Chowk Center, 28-2-11, Velpur Road, Tanuku, Andhra Pradesh. Opposite Reliance Digital.',phone:'+91 97019 19654',email:'',gstin:'',state:'',placeOfSupply:'',hsnSac:'',timezone:'Asia/Kolkata',currency:'INR',invoicePrefix:'',invoiceDigits:6,receiptFooter:'Thank you for dining with Dawat.',receiptWidth:'80',taxConfigured:false,noTaxConfirmed:false,defaultTaxProfileId:null,roundOff:false,packingPaise:0,deliveryPaise:0,serviceChargeBps:0,chargeTaxProfileId:null,tipsEnabled:false,orderTypes:['Dine-in','Takeaway','Delivery','Online'],defaultOrderType:'Takeaway',paymentMethods:['Cash','UPI','Card','Bank Transfer','Wallet','Other'],upiId:'',upiName:'',manualDiscountsEnabled:false,discountLimitBps:null,requireVoidApproval:true,requireRefundApproval:true,requireCashApproval:true,autoDeduct:false,allowNegativeStock:false,lowStockAlerts:true,loyaltyEnabled:false,loyaltyEarnPaise:null,loyaltyEarnPoints:null,loyaltyFixedPoints:null,loyaltyRedeemPaise:null,loyaltyMinPoints:null,loyaltyExpiryDays:null,sessionMinutes:30,pinLength:6,notificationOverdueMinutes:null,requireShift:true,liveBillingEnabled:false};
export const permissions=['dashboard.view','order.create','order.edit','order.void','order.cancel','order.discount','order.discount.manual','order.charges','order.transfer','order.merge','order.split','order.completed.view','bill.finalize','bill.reprint','bill.refund','bill.cancel','payment.accept','cash.adjust','cash.drawer','shift.open','shift.close','menu.view','menu.edit','menu.price','kitchen.view','kitchen.update','inventory.view','inventory.manage','inventory.count','inventory.wastage','purchase.create','purchase.receive','supplier.manage','customer.manage','expense.manage','report.financial','staff.manage','settings.manage','audit.view','backup.export'];
export const roles:Record<string,string[]>={Owner:permissions,Admin:permissions,Manager:permissions.filter(p=>!['staff.manage','backup.export'].includes(p)),Cashier:['order.create','order.edit','order.discount','order.completed.view','order.split','bill.finalize','bill.reprint','payment.accept','shift.open','shift.close','menu.view','customer.manage'],Waiter:['order.create','order.edit','order.transfer','menu.view','kitchen.view'],Kitchen:['kitchen.view','kitchen.update','menu.view'],'Inventory Manager':['inventory.view','inventory.manage','inventory.count','inventory.wastage','purchase.create','purchase.receive','supplier.manage','menu.view']};
export type Actor={id:string;name:string;role:string;permissions:string[];locationId:string;sessionId:string;terminalId:string|null;platformId:string|null};
export const can=(a:Actor,p:string)=>a.permissions.includes(p);
export function permit(a:Actor,p:string){ensure(can(a,p),'Your role does not allow this action.',403,'FORBIDDEN');}
export function localDate(time=Date.now(),tz='Asia/Kolkata'){return new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(time));}
export function fiscalYear(time=Date.now(),tz='Asia/Kolkata'){const [y,m]=localDate(time,tz).split('-').map(Number),start=m<4?y-1:y;return `${String(start).slice(2)}-${String(start+1).slice(2)}`;}
export function calculate(lines:Line[],orderDiscount=0,charges:{packing?:number;delivery?:number;serviceBps?:number;tips?:number;tax?:Tax|null}={},roundOff=false){
 const gross=lines.map(l=>int(l.quantity,1,999)*int(l.unitPaise+ l.modifierPaise)),afterItem=gross.map((v,i)=>{int(lines[i].discountPaise,0,v);return v-lines[i].discountPaise;});int(orderDiscount,0,afterItem.reduce((a,b)=>a+b,0));const discounts=allocate(orderDiscount,afterItem);const components:Record<string,number>={};
 const taxAmount=(amount:number,tax:Tax|null)=>{const rate=tax?.components.reduce((s,c)=>s+int(c.rateBps,0,10000),0)||0;const taxable=tax?.inclusive?Math.round(amount*10000/(10000+rate)):amount;const taxPaise=tax?.inclusive?amount-taxable:Math.round(amount*rate/10000);if(tax&&rate)allocate(taxPaise,tax.components.map(c=>c.rateBps)).forEach((v,i)=>{const key=tax.components[i].name+' '+(tax.components[i].rateBps/100)+'%';components[key]=(components[key]||0)+v;});return{taxablePaise:taxable,taxPaise,totalPaise:taxable+taxPaise};};
 const items=lines.map((l,i)=>({...l,grossPaise:gross[i],discountPaise:l.discountPaise+discounts[i],...taxAmount(afterItem[i]-discounts[i],l.tax)}));const taxable=items.reduce((s,i)=>s+i.taxablePaise,0);const chargeBase=int(charges.packing||0)+int(charges.delivery||0)+Math.round(taxable*int(charges.serviceBps||0,0,10000)/10000);const ct=taxAmount(chargeBase,charges.tax||null),tips=int(charges.tips||0);const raw=items.reduce((s,i)=>s+i.totalPaise,0)+ct.totalPaise+tips;const total=roundOff?Math.round(raw/100)*100:raw;int(total);
 return{items,subtotalPaise:gross.reduce((a,b)=>a+b,0),discountPaise:lines.reduce((a,l)=>a+l.discountPaise,orderDiscount),taxablePaise:taxable+ct.taxablePaise,taxPaise:items.reduce((s,i)=>s+i.taxPaise,0)+ct.taxPaise,chargesPaise:chargeBase,tipsPaise:tips,roundPaise:total-raw,totalPaise:total,components};
}
export type Bill=ReturnType<typeof calculate>;
