'use client';
import {api,Data,decode,money} from './client';
import type {Bill,Settings} from './domain';
export interface PrintAdapter{print(kind:'bill'|'kot',id:string):Promise<void>}
const escape=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function receiptHtml(result:Data){const doc=result.document as Data,kind=result.kind,copy=result.reprint?'REPRINT':'ORIGINAL';let body='',width='80';if(kind==='bill'){const snap=decode<{calculation:Bill;settings:Settings;tables:string[];cashier:string;finalizedAt:string}>(doc.snapshot_json,null as unknown as {calculation:Bill;settings:Settings;tables:string[];cashier:string;finalizedAt:string}),b=snap.calculation,s=snap.settings;width=s.receiptWidth;body=`<header><h1>${escape(s.restaurantName)}</h1><p>${escape(s.legalName)}</p><p>${escape(s.address)}</p><p>${escape(s.phone)}</p>${s.gstin?'<p>GSTIN: '+escape(s.gstin)+'</p>':''}<h2>Invoice ${escape(doc.number)}</h2><p>${escape(snap.finalizedAt)} · ${copy}</p>${snap.tables.length?'<p>Table: '+escape(snap.tables.join(', '))+'</p>':''}</header><table><thead><tr><th>Item</th><th>Qty</th><th>Amount</th></tr></thead><tbody>${b.items.map(l=>`<tr><td>${escape(l.name)}${l.modifiers.length?'<small>'+escape(l.modifiers.map(m=>m.name).join(', '))+'</small>':''}</td><td>${l.quantity}</td><td>${escape(money(l.grossPaise))}</td></tr>`).join('')}</tbody></table><section><p>Items at menu price <b>${escape(money(b.subtotalPaise))}</b></p>${b.discountPaise?'<p>Discount <b>−'+escape(money(b.discountPaise))+'</b></p>':''}${b.chargesPaise?'<p>Charges at configured price <b>'+escape(money(b.chargesPaise))+'</b></p>':''}<p>Amount before tax (after discounts) <b>${escape(money(b.taxablePaise))}</b></p>${Object.entries(b.components).map(([name,value])=>'<p>'+escape(name)+' <b>'+escape(money(value))+'</b></p>').join('')}${b.tipsPaise?'<p>Tip <b>'+escape(money(b.tipsPaise))+'</b></p>':''}${b.roundPaise?'<p>Round off <b>'+escape(money(b.roundPaise))+'</b></p>':''}<p class="total">TOTAL <b>${escape(money(b.totalPaise))}</b></p></section><section>${(doc.payments as Data[]||[]).map(p=>'<p>'+escape(p.method)+' <b>'+escape(money(p.amount_paise))+'</b></p>'+(Number(p.change_paise)>0?'<p>Change <b>'+escape(money(p.change_paise))+'</b></p>':'')).join('')}${(doc.refunds as Data[]||[]).map(r=>'<p>Refund ('+escape(r.method)+') <b>'+escape(money(r.amount_paise))+'</b></p>').join('')}${(doc.events as Data[]||[]).some(e=>e.action==='Cancelled')?'<h2>CANCELLED</h2>':''}</section><footer><p>Served by ${escape(snap.cashier)}</p><p>${escape(s.receiptFooter)}</p></footer>`;}else{body=`<header><h1>KITCHEN TICKET</h1><h2>${escape(doc.number)}</h2><p>${escape(doc.created_at)} · ${copy}</p></header>${(doc.items as Data[]).map(row=>{const l=decode<Data>(row.snapshot_json,{});return '<div class="kot-line"><h2>'+escape(row.quantity)+' × '+escape(l.name)+'</h2>'+((l.modifiers as Data[]||[]).length?'<p>'+escape((l.modifiers as Data[]).map(m=>m.name).join(', '))+'</p>':'')+(l.note?'<strong>NOTE: '+escape(l.note)+'</strong>':'')+(l.seat?'<p>Seat '+escape(l.seat)+'</p>':'')+'</div>';}).join('')}`;}
return '<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Dawat '+escape(kind)+' '+escape(doc.number)+'</title><style>@page{size:'+(width==='A4'?'A4':width+'mm auto')+';margin:5mm}body{font:12px ui-monospace,monospace;color:#000;width:'+(width==='A4'?'auto':(Number(width)-10)+'mm')+';margin:12px auto}h1{font-size:21px}h2{font-size:15px}p{margin:6px 0}header,footer{text-align:center}table{width:100%;border-collapse:collapse}th,td{padding:7px 0;border-bottom:1px dashed #999;text-align:left;vertical-align:top}td:last-child,th:last-child{text-align:right;white-space:nowrap}td:first-child{padding-right:8px}small{display:block}section{border-bottom:1px dashed #999;padding:8px 0}section p{display:flex;justify-content:space-between;gap:10px}.total{font-size:17px;font-weight:bold}.kot-line{padding:12px 0;border-bottom:1px dashed #999}button{padding:12px 20px;margin:12px 0;cursor:pointer}@media print{button{display:none}}</style></head><body>'+body+'<button onclick="window.print()">Print / Save PDF</button></body></html>';
}
export const browserPrinter:PrintAdapter={async print(kind,id){const win=window.open('','_blank');if(!win)throw new Error('Allow the receipt window in your browser, then try printing again.');win.opener=null;try{const result=await api('print',{kind,id});win.document.open();win.document.write(receiptHtml(result));win.document.close();win.focus();win.print();}catch(e){win.close();throw e;}}};
