import {pbkdf2Sync} from 'node:crypto';
import {mkdtempSync,readFileSync,rmSync,existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {decryptBackup,restoreBackup} from '../scripts/restore-backup.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {SQLiteD1} from './sqlite-adapter.mjs';
import {calculate,allocate,dayStart,csv,derivePasswordKey,encryptedBackup} from '../.test-build/engine.mjs';
// All people, accounts, terminals, taxes, tables, stock and transactions below
// are isolated QA fixtures. They are never production seeds.
import {Client,fixture,order,action} from './fixtures.mjs';
test('verified menu import preserves 91 prices, paise precision and 3 unset signatures',async()=>{const f=await fixture();assert.equal(f.bootstrap.menu.length,94);assert.equal(f.bootstrap.menu.filter(m=>m.price_paise===null).length,3);assert.equal(f.bootstrap.menu.find(m=>m.name==='Veg Manchow Soup').price_paise,14050);assert.equal(f.bootstrap.catalog.tables.length,0);assert.equal((await f.owner.get('records/inventory')).total,0);});
test('money arithmetic: inclusive/exclusive components, discount allocation and rounding',()=>{assert.deepEqual(allocate(100,[1,1,1]),[34,33,33]);const line={id:'a',menuItemId:'a',name:'QA',category:'QA',quantity:1,unitPaise:10500,modifierPaise:0,modifiers:[],note:'',seat:'',discountPaise:0,tax:{id:'qa',name:'QA',inclusive:true,components:[{name:'QA component A',rateBps:250},{name:'QA component B',rateBps:250}]}};const bill=calculate([line]);assert.equal(bill.taxablePaise,10000);assert.equal(bill.taxPaise,500);assert.equal(bill.totalPaise,10500);assert.equal(calculate([{...line,unitPaise:10000,tax:{...line.tax,inclusive:false}}]).totalPaise,10500);assert.equal(calculate([{...line,unitPaise:14050,tax:null}],0,{},true).roundPaise,50);});
test('dine-in: quantities and notes, incremental KOT, kitchen ready, discount, bill, cash and table close',async()=>{const f=await fixture();const table=await f.owner.post('resources/tables',{values:{name:'QA-T01',capacity:4}});let o=await order(f,'Dine-in',{tableId:table.id,guestCount:2,items:[{menuItemId:f.item.id,quantity:1,note:'QA less spicy'},{menuItemId:f.second.id,quantity:1}]});o=await action(f,o,'line',{lineId:o.items.find(x=>x.menu_item_id===f.item.id).id,quantity:2,note:'QA less spicy',seat:'1'});o=await action(f,o,'kot');const initial=f.db.sqlite.prepare('SELECT SUM(quantity) n FROM kot_items').get().n;assert.equal(initial,3);o=await action(f,o,'items',{items:[{menuItemId:f.item.id,quantity:1}]});o=await action(f,o,'kot');assert.equal(f.db.sqlite.prepare('SELECT SUM(quantity) n FROM kot_items').get().n,4);const tickets=(await f.owner.get('records/kitchen')).rows;assert.equal(tickets.length,2);assert.equal(tickets.flatMap(t=>t.items).filter(i=>JSON.parse(i.snapshot_json).note==='QA less spicy').length,1);for(const ticket of tickets){await f.owner.post('kitchen/'+ticket.id,{version:ticket.version,status:'Preparing'});const current=f.db.sqlite.prepare('SELECT version FROM kots WHERE id=?').get(ticket.id);await f.owner.post('kitchen/'+ticket.id,{version:current.version,status:'Ready'});}o=await f.owner.get('orders/'+o.id);assert.equal(o.status,'Ready');o=await action(f,o,'discount',{type:'fixed',value:100,reason:'QA approved discount'});o=await action(f,o,'bill');assert.equal(o.invoice.discount_paise,100);const total=o.invoice.total_paise;o=await action(f,o,'pay',{method:'Cash',amountPaise:total,tenderedPaise:total+500});assert.equal(o.invoice.payments[0].change_paise,500);o=await action(f,o,'state',{action:'close'});assert.equal(o.status,'Closed');assert.equal(f.db.sqlite.prepare('SELECT status FROM dining_tables WHERE id=?').get(table.id).status,'Cleaning');assert.equal(f.db.sqlite.prepare('SELECT COUNT(*) n FROM table_assignments').get().n,0);});
test('takeaway UPI is manual-confirmed, receipt and reprint are audited',async()=>{const f=await fixture();let o=await action(f,await order(f),'bill');await f.owner.post('orders/'+o.id+'/pay',{version:o.version,method:'UPI',amountPaise:o.invoice.total_paise},400);o=await action(f,o,'pay',{method:'UPI',amountPaise:o.invoice.total_paise,confirmed:true,reference:'QA-UPI'});const first=await f.owner.post('print',{kind:'bill',id:o.invoice.id}),second=await f.owner.post('print',{kind:'bill',id:o.invoice.id});assert.equal(first.reprint,false);assert.equal(second.reprint,true);assert.equal(f.db.sqlite.prepare("SELECT COUNT(*) n FROM audit_logs WHERE action='Print requested'").get().n,2);});
test('cash + UPI partial payments reconcile and duplicate retries create one payment',async()=>{const f=await fixture();let o=await action(f,await order(f),'bill');const key=crypto.randomUUID(),p={version:o.version,method:'Cash',amountPaise:100,tenderedPaise:100};const a=await f.owner.post('orders/'+o.id+'/pay',p,200,key),b=await f.owner.post('orders/'+o.id+'/pay',p,200,key);assert.equal(a.paymentId,b.paymentId);assert.equal(f.db.sqlite.prepare('SELECT COUNT(*) n FROM payments').get().n,1);await f.owner.post('orders/'+o.id+'/pay',{...p,amountPaise:99},409,key);o=await f.owner.get('orders/'+o.id);assert.equal(o.status,'Part paid');o=await action(f,o,'pay',{method:'UPI',amountPaise:o.invoice.total_paise-100,confirmed:true});assert.equal(o.status,'Paid');});
test('bill shares by item quantities sum exactly and prevent overspending a share',async()=>{const f=await fixture();let o=await order(f,'Takeaway',{items:[{menuItemId:f.item.id,quantity:3,seat:'1'}]});o=await action(f,o,'bill');const line=o.items[0];o=await action(f,o,'split',{mode:'items',shares:[{label:'QA guest 1',items:[{id:line.id,quantity:1}]},{label:'QA guest 2',items:[{id:line.id,quantity:2}]}]});assert.equal(o.invoice.shares.reduce((s,x)=>s+x.amount_paise,0),o.invoice.total_paise);const share=o.invoice.shares[0];await f.owner.post('orders/'+o.id+'/pay',{version:o.version,method:'Cash',shareId:share.id,amountPaise:share.amount_paise+1,tenderedPaise:share.amount_paise+1},400);o=await action(f,o,'pay',{method:'Cash',shareId:share.id,amountPaise:share.amount_paise,tenderedPaise:share.amount_paise});assert.equal(o.status,'Part paid');});
test('table move and merge retain lines and ticket history',async()=>{const f=await fixture();const ids=[];for(const name of ['QA-A','QA-B','QA-C'])ids.push((await f.owner.post('resources/tables',{values:{name,capacity:4}})).id);let a=await order(f,'Dine-in',{tableId:ids[0]});a=await action(f,a,'kot');a=await action(f,a,'table',{action:'move',tableId:ids[1]});assert.equal(a.tables[0].id,ids[1]);const b=await order(f,'Dine-in',{tableId:ids[2]});a=await action(f,a,'table',{action:'merge',otherOrderId:b.id,otherVersion:b.version});assert.equal(a.tables.length,2);assert.equal(a.items.length,2);assert.equal(a.kots.length,1);assert.equal(f.db.sqlite.prepare('SELECT status FROM orders WHERE id=?').get(b.id).status,'Merged');});
test('sold-out items and stale menu prices cannot be ordered',async()=>{const f=await fixture();await f.owner.post('menu/availability',{id:f.item.id,version:f.item.version,status:'Sold out'});await f.owner.post('orders/create',{id:crypto.randomUUID(),type:'Takeaway',items:[{menuItemId:f.item.id,quantity:1}]},400);await f.owner.post('orders/create',{id:crypto.randomUUID(),type:'Takeaway',items:[{menuItemId:f.second.id,quantity:1,expectedPricePaise:1}]},409);});
test('staff PIN requires a paired terminal; cashier price changes are forbidden',async()=>{const f=await fixture();await f.owner.post('staff',{name:'QA Cashier',code:'QA-CASH',roleId:'Cashier',pin:'593817',active:true});const cashier=new Client(f.db,'qa-owner');await cashier.post('auth/login',{mode:'pin',login:'QA-CASH',secret:'593817'},403);cashier.cookies.dawat_device=f.owner.cookies.dawat_device;await cashier.post('auth/login',{mode:'pin',login:'QA-CASH',secret:'593817'});await cashier.post('resources/menu',{id:f.item.id,version:f.item.version,values:{price_paise:1}},403);await cashier.get('bootstrap');});
test('manager PIN authorizes exact cashier refund; approval cannot be reused',async()=>{const f=await fixture();await f.owner.post('auth/credentials',{pin:'593817'});await f.owner.post('staff',{name:'QA Cashier',code:'QA-CASH',roleId:'Cashier',pin:'683951'});let o=await action(f,await order(f),'bill');o=await action(f,o,'pay',{method:'Cash',amountPaise:o.invoice.total_paise,tenderedPaise:o.invoice.total_paise});const cashier=new Client(f.db,'qa-owner');cashier.cookies.dawat_device=f.owner.cookies.dawat_device;await cashier.post('auth/login',{mode:'pin',login:'QA-CASH',secret:'683951'});const request={version:o.version,mode:'partial',amountPaise:100,method:'Cash',reason:'QA authorized refund'};const missing=await cashier.post('orders/'+o.id+'/refund',request,403);assert.equal(missing.code,'APPROVAL_REQUIRED');const approval=await cashier.post('auth/approve',{code:'OWNER',pin:'593817',action:'bill.refund',entityId:o.id,request});await cashier.post('orders/'+o.id+'/refund',{...request,approvalId:approval.id});await cashier.post('orders/'+o.id+'/refund',{...request,approvalId:approval.id},403);assert.equal(f.db.sqlite.prepare('SELECT COUNT(*) n FROM refunds').get().n,1);});
test('void audit persists and finalized financial rows reject updates and deletes',async()=>{const f=await fixture();let o=await order(f,'Takeaway',{items:[{menuItemId:f.item.id,quantity:1},{menuItemId:f.second.id,quantity:1}]});o=await action(f,o,'void',{lineId:o.items[0].id,reason:'QA correction'});assert.equal(o.items.filter(x=>x.voided).length,1);assert.equal(f.db.sqlite.prepare("SELECT COUNT(*) n FROM audit_logs WHERE action='Item voided'").get().n,1);o=await action(f,o,'bill');assert.throws(()=>f.db.sqlite.prepare('UPDATE invoices SET total_paise=1 WHERE id=?').run(o.invoice.id),/immutable/);assert.throws(()=>f.db.sqlite.exec('DELETE FROM audit_logs'),/immutable/);assert.throws(()=>f.db.sqlite.prepare('UPDATE order_items SET quantity=99 WHERE order_id=?').run(o.id),/immutable/);});
test('recipe consumption, wastage and goods receipt are atomic and use real counts',async()=>{const f=await fixture();const item=await f.owner.post('resources/inventory',{values:{name:'QA Ingredient',type:'Raw ingredient',unit_id:'kg'}});assert.equal(f.db.sqlite.prepare('SELECT quantity_milli FROM inventory_items WHERE id=?').get(item.id).quantity_milli,null);await f.owner.post('inventory/adjust',{id:item.id,version:1,type:'Opening',quantityMilli:10000,averageCostPaise:5000,reason:'QA physical count'});await f.owner.post('inventory/recipe',{menuItemId:f.item.id,yieldQty:1,items:[{inventoryItemId:item.id,quantityMilli:250}]});const boot=await f.owner.get('bootstrap');await f.owner.post('settings',{version:boot.settingsVersion,values:{autoDeduct:true}});await action(f,await order(f),'bill');assert.equal(f.db.sqlite.prepare('SELECT quantity_milli FROM inventory_items WHERE id=?').get(item.id).quantity_milli,9750);let stock=f.db.sqlite.prepare('SELECT * FROM inventory_items WHERE id=?').get(item.id);await f.owner.post('inventory/wastage',{id:item.id,version:stock.version,quantityMilli:100,reason:'QA spill'});assert.equal(f.db.sqlite.prepare('SELECT quantity_milli FROM inventory_items WHERE id=?').get(item.id).quantity_milli,9650);const supplier=await f.owner.post('resources/suppliers',{values:{name:'QA Supplier'}});const purchase=await f.owner.post('purchases/create',{supplierId:supplier.id,date:'2026-09-08',items:[{inventoryItemId:item.id,quantityMilli:1000,unitCostPaise:5000}]});assert.equal(f.db.sqlite.prepare('SELECT quantity_milli FROM inventory_items WHERE id=?').get(item.id).quantity_milli,9650);const detail=await f.owner.get('detail/purchases/'+purchase.id);await f.owner.post('purchases/'+purchase.id+'/receive',{version:detail.version,type:'Receipt',items:[{id:detail.items[0].id,quantityMilli:1000}]});assert.equal(f.db.sqlite.prepare('SELECT quantity_milli FROM inventory_items WHERE id=?').get(item.id).quantity_milli,10650);});
test('insufficient recipe stock rolls back invoice, sequence increment, and all movements',async()=>{const f=await fixture();const item=await f.owner.post('resources/inventory',{values:{name:'QA Scarce',type:'Raw ingredient',unit_id:'each'}});await f.owner.post('inventory/adjust',{id:item.id,version:1,type:'Opening',quantityMilli:0,reason:'QA empty count'});await f.owner.post('inventory/recipe',{menuItemId:f.item.id,yieldQty:1,items:[{inventoryItemId:item.id,quantityMilli:1000}]});const boot=await f.owner.get('bootstrap');await f.owner.post('settings',{version:boot.settingsVersion,values:{autoDeduct:true}});const o=await order(f);await f.owner.post('orders/'+o.id+'/bill',{version:o.version},400);assert.equal(f.db.sqlite.prepare('SELECT COUNT(*) n FROM invoices').get().n,0);assert.equal(f.db.sqlite.prepare("SELECT COUNT(*) n FROM stock_movements WHERE type='Consumption'").get().n,0);});
test('stock count rejects movements after draft and confirms an unchanged count',async()=>{const f=await fixture();const item=await f.owner.post('resources/inventory',{values:{name:'QA Count',type:'Packaging',unit_id:'each'}});const count=await f.owner.post('stock-counts/create',{items:[{inventoryItemId:item.id,actualMilli:10000}]});await f.owner.post('inventory/adjust',{id:item.id,version:1,type:'Opening',quantityMilli:9000,reason:'QA opening'});await f.owner.post('stock-counts/'+count.id,{version:1},409);const fresh=await f.owner.post('stock-counts/create',{items:[{inventoryItemId:item.id,actualMilli:9500}]});await f.owner.post('stock-counts/'+fresh.id,{version:1});assert.equal(f.db.sqlite.prepare('SELECT quantity_milli FROM inventory_items WHERE id=?').get(item.id).quantity_milli,9500);});
test('shift expected cash includes collections, refunds and expenses; stale close fails',async()=>{const f=await fixture();let o=await action(f,await order(f),'bill');const total=o.invoice.total_paise;o=await action(f,o,'pay',{method:'Cash',amountPaise:total,tenderedPaise:total+1000});o=await action(f,o,'refund',{mode:'partial',amountPaise:100,method:'Cash',reason:'QA refund'});await f.owner.post('expenses/create',{amountPaise:500,date:'2026-09-08',category:'Other',method:'Cash',description:'QA cash expense'});const shiftId=f.bootstrap.activeShift.shift.id,summary=await f.owner.get('shifts/'+shiftId);assert.equal(summary.expectedPaise,100000+total-100-500);await f.owner.post('shifts/'+shiftId+'/close',{version:1,actualPaise:summary.expectedPaise},409);await f.owner.post('shifts/'+shiftId+'/close',{version:summary.shift.version,actualPaise:summary.expectedPaise-10,reason:'QA variance'});assert.equal(f.db.sqlite.prepare('SELECT variance_paise FROM shifts WHERE id=?').get(shiftId).variance_paise,-10);});
test('two terminals editing an order produce a conflict and preserve the winning write',async()=>{const f=await fixture(),o=await order(f),payload={version:o.version,items:[{menuItemId:f.second.id,quantity:1}]};await f.owner.post('orders/'+o.id+'/items',payload);await f.owner.post('orders/'+o.id+'/items',payload,409);assert.equal(f.db.sqlite.prepare('SELECT COUNT(*) n FROM order_items WHERE order_id=?').get(o.id).n,2);});
test('offline-style create retry preserves one order with its original identifier',async()=>{const f=await fixture(),id=crypto.randomUUID(),key=crypto.randomUUID(),payload={id,type:'Takeaway',items:[{menuItemId:f.item.id,quantity:2,note:'QA disconnected draft'}]};await f.owner.post('orders/create',payload,200,key);await f.owner.post('orders/create',payload,200,key);assert.equal(f.db.sqlite.prepare('SELECT COUNT(*) n FROM orders WHERE id=?').get(id).n,1);});
test('CSRF, role checks, unknown routes and session lock fail closed',async()=>{const f=await fixture();await f.owner.request('orders/create',{},403,crypto.randomUUID(),{origin:'https://attacker.invalid'});await f.owner.post('unknown',{},404);await f.owner.post('auth/credentials',{pin:'593817'});await f.owner.post('auth/lock');await f.owner.request('bootstrap',undefined,423);await f.owner.post('auth/unlock',{secret:'593817'});await f.owner.get('bootstrap');});
test('tax/profile updates never change an already frozen invoice',async()=>{const f=await fixture();let o=await action(f,await order(f),'bill');const original=o.invoice.snapshot_json;const b=await f.owner.get('bootstrap');await f.owner.post('settings',{version:b.settingsVersion,values:{restaurantName:'QA changed receipt heading'}});o=await f.owner.get('orders/'+o.id);assert.equal(o.invoice.snapshot_json,original);});
test('report dates respect restaurant timezone and CSV blocks spreadsheet formulas',()=>{assert.equal(dayStart('2026-09-08','Asia/Kolkata'),'2026-09-07T18:30:00.000Z');assert.match(csv([{name:'=HYPERLINK("bad")',amount:1}]),/'=HYPERLINK/);assert.throws(()=>dayStart('2026-02-30','Asia/Kolkata'));});

test('portable password derivation matches native PBKDF2 at the full work factor',async()=>{
 const salt=Uint8Array.from({length:16},(_,i)=>i),input='isolated QA derivation vector';
 assert.deepEqual(Buffer.from(await derivePasswordKey(input,salt)),pbkdf2Sync(input,salt,600000,32,'sha256'));
});
test('encrypted recovery restores ledgers and receipts, checks integrity, and refuses overwrite or tampering',async()=>{
 const f=await fixture();let o=await action(f,await order(f),'bill');o=await action(f,o,'pay',{method:'Cash',amountPaise:o.invoice.total_paise,tenderedPaise:o.invoice.total_paise});o=await action(f,o,'refund',{mode:'partial',amountPaise:100,method:'Cash',reason:'QA recovery refund'});
 const open=await order(f),b=await f.owner.get('bootstrap'),bytes=Buffer.from('%PDF-1.4\nQA receipt fixture\n'),key=b.actor.locationId+'/receipts/qa-receipt';
 f.db.sqlite.prepare('INSERT INTO attachments(id,location_id,name,mime,size,object_key,uploaded_by,created_at) VALUES(?,?,?,?,?,?,?,?)').run('qa-receipt',b.actor.locationId,'qa-receipt.pdf','application/pdf',bytes.length,key,b.actor.id,new Date().toISOString());
 const bucket={async get(objectKey){assert.equal(objectKey,key);return{async arrayBuffer(){return bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength);}};}};
 const pass='isolated QA recovery passphrase',encrypted=await encryptedBackup({db:f.db,actor:b.actor,settings:b.settings,key:''},pass,bucket),backup=decryptBackup(encrypted,pass),root=mkdtempSync(join(tmpdir(),'dawat-recovery-'));
 try{const output=join(root,'restored'),v=restoreBackup(backup,output);assert.equal(v.foreignKeys,'passed');assert.equal(v.receiptFiles,1);assert.equal(v.counts.invoices,1);assert.deepEqual(readFileSync(join(output,'receipts',key)),bytes);const db=new SQLiteD1(join(output,'restaurant.sqlite'));
  assert.equal(db.sqlite.prepare('SELECT total_paise FROM invoices').get().total_paise,o.invoice.total_paise);assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM sessions').get().n,0);assert.equal(db.sqlite.prepare('SELECT device_hash FROM terminals').get().device_hash,null);assert.equal(JSON.parse(db.sqlite.prepare('SELECT data_json FROM settings').get().data_json).liveBillingEnabled,false);
  assert.throws(()=>db.sqlite.prepare('UPDATE order_items SET order_id=? WHERE id=?').run(open.id,o.items[0].id),/immutable/);assert.throws(()=>db.sqlite.exec('DELETE FROM payments'),/immutable/);db.sqlite.close();
  assert.throws(()=>restoreBackup(backup,output),/already exists/);assert.throws(()=>decryptBackup(encrypted,'wrong QA passphrase'),/authentication failed/);const corrupt=Uint8Array.from(encrypted);corrupt[corrupt.length-1]^=1;assert.throws(()=>decryptBackup(corrupt,pass),/authentication failed/);
  const damaged=structuredClone(backup);damaged.tables.payments[0].invoice_id='missing-qa-invoice';assert.throws(()=>restoreBackup(damaged,join(root,'invalid')),/integrity|FOREIGN KEY/i);assert.equal(existsSync(join(root,'invalid')),false);
 }finally{rmSync(root,{recursive:true,force:true});}
});
test('loyalty is earned once on full collection, reserved at billing, and released on unpaid cancellation',async()=>{
 const f=await fixture(),customer=await f.owner.post('resources/customers',{values:{name:'QA Loyalty',phone:'0000000000'}});let b=await f.owner.get('bootstrap');await f.owner.post('settings',{version:b.settingsVersion,values:{loyaltyEnabled:true,loyaltyFixedPoints:20,loyaltyRedeemPaise:100,loyaltyMinPoints:1,loyaltyExpiryDays:30}});
 let o=await action(f,await order(f,'Takeaway',{customerId:customer.id}),'bill');assert.equal((await f.owner.get('detail/customers/'+customer.id)).loyalty.points,0);o=await action(f,o,'pay',{method:'Cash',amountPaise:o.invoice.total_paise,tenderedPaise:o.invoice.total_paise});assert.equal((await f.owner.get('detail/customers/'+customer.id)).loyalty.points,20);
 let other=await order(f,'Takeaway',{customerId:customer.id});other=await action(f,other,'loyalty',{points:10});assert.equal((await f.owner.get('detail/customers/'+customer.id)).loyalty.points,20);other=await action(f,other,'bill');assert.equal((await f.owner.get('detail/customers/'+customer.id)).loyalty.points,10);await action(f,other,'cancel-invoice',{reason:'QA unpaid cancellation'});assert.equal((await f.owner.get('detail/customers/'+customer.id)).loyalty.points,20);
 await action(f,o,'refund',{mode:'full',method:'Cash',reason:'QA full refund'});assert.equal((await f.owner.get('detail/customers/'+customer.id)).loyalty.points,0);
});
test('expired loyalty credits cannot be spent or resurrected by later debits',async()=>{
 const f=await fixture(),customer=await f.owner.post('resources/customers',{values:{name:'QA Expiry'}}),b=await f.owner.get('bootstrap');
 const add=(id,points,created,expiry)=>f.db.sqlite.prepare('INSERT INTO loyalty_transactions(id,customer_id,points,type,reference,expires_at,created_at,actor_id) VALUES(?,?,?,?,?,?,?,?)').run(id,customer.id,points,points>0?'Earn':'Redeem',id,expiry,created,b.actor.id);
 add('qa-expired',50,'2020-01-01T00:00:00.000Z','2020-02-01T00:00:00.000Z');add('qa-valid',20,'2020-03-01T00:00:00.000Z',null);add('qa-use',-5,'2020-04-01T00:00:00.000Z',null);assert.equal((await f.owner.get('detail/customers/'+customer.id)).loyalty.points,15);
});
test('supplier cash payments and purchase returns reconcile stock, credits and the cash shift',async()=>{
 const f=await fixture(),stock=await f.owner.post('resources/inventory',{values:{name:'QA Purchase return',type:'Raw ingredient',unit_id:'kg'}});await f.owner.post('inventory/adjust',{id:stock.id,version:1,type:'Opening',quantityMilli:0,reason:'QA count'});const supplier=await f.owner.post('resources/suppliers',{values:{name:'QA Credit Supplier'}}),purchase=await f.owner.post('purchases/create',{supplierId:supplier.id,date:'2026-09-09',items:[{inventoryItemId:stock.id,quantityMilli:1000,unitCostPaise:5000}]});let p=await f.owner.get('detail/purchases/'+purchase.id);await f.owner.post('purchases/'+p.id+'/receive',{version:p.version,type:'Receipt',items:[{id:p.items[0].id,quantityMilli:1000}]});p=await f.owner.get('detail/purchases/'+p.id);await f.owner.post('purchases/'+p.id+'/pay',{version:p.version,method:'Cash',amountPaise:5000});p=await f.owner.get('detail/purchases/'+p.id);await f.owner.post('purchases/'+p.id+'/receive',{version:p.version,type:'Return',reason:'QA rejected quantity',items:[{id:p.items[0].id,quantityMilli:200}]});assert.equal(f.db.sqlite.prepare('SELECT quantity_milli FROM inventory_items WHERE id=?').get(stock.id).quantity_milli,800);const report=await f.owner.get('reports?type=supplier-outstanding');assert.equal(report.rows[0].outstanding_paise,-1000);assert.equal((await f.owner.get('shifts/'+f.bootstrap.activeShift.shift.id)).expectedPaise,95000);
});
test('tips and configured charge overrides freeze with an invoice',async()=>{
 const f=await fixture();const b=await f.owner.get('bootstrap');await f.owner.post('settings',{version:b.settingsVersion,values:{tipsEnabled:true}});let o=await order(f);o=await action(f,o,'charges',{packingPaise:500,deliveryPaise:0,serviceBps:0,tipsPaise:200,reason:'QA guest tip'});assert.equal(o.preview.totalPaise,o.subtotal_paise+700);o=await action(f,o,'bill');assert.equal(JSON.parse(o.invoice.snapshot_json).calculation.tipsPaise,200);await f.owner.post('orders/'+o.id+'/charges',{version:o.version,tipsPaise:0,reason:'QA attempt'},400);
});
test('customer phone search works and incomplete cost data does not become a profit estimate',async()=>{
 const f=await fixture();await f.owner.post('resources/customers',{values:{name:'QA Phone Lookup',phone:'0000000099'}});assert.equal((await f.owner.get('records/customers?q=0000000099')).total,1);await action(f,await order(f),'bill');const report=await f.owner.get('reports?type=profitability');assert.equal(report.rows[0].estimated_gross_margin_paise,null);
});
test('report breakdowns reconcile split collections, staff activity, tax snapshots and expenses',async()=>{
 const f=await fixture();let o=await action(f,await order(f),'bill');const total=o.invoice.total_paise;o=await action(f,o,'pay',{method:'Cash',amountPaise:1000,tenderedPaise:1000});await action(f,o,'pay',{method:'UPI',amountPaise:total-1000,confirmed:true});
 let draft=await order(f);await action(f,draft,'void',{lineId:draft.items[0].id,reason:'QA wrong dish'});
 const day=new Date().toISOString().slice(0,10);await f.owner.post('expenses/create',{date:day,category:'Cleaning',method:'Cash',amountPaise:300,description:'QA report expense'});
 const split=await f.owner.get('reports?type=split-payments');assert.equal(split.rows[0].collected_paise,total);assert.equal(split.rows[0].cash_paise,1000);assert.equal(split.rows[0].upi_paise,total-1000);
 const staff=await f.owner.get('reports?type=staff');const owner=staff.rows.find(s=>s.staff_id===f.bootstrap.actor.id);assert.equal(owner.invoices_finalized,1);assert.equal(owner.revenue_paise,total);assert.equal(owner.voids,1);assert.ok(owner.void_value_paise>0);
 const taxable=await f.owner.get('reports?type=tax-invoices');assert.equal(taxable.rows[0].taxable_sales_paise,JSON.parse(o.invoice.snapshot_json).calculation.taxablePaise);
 for(const type of ['expense-categories','expense-daily','expense-monthly'])assert.equal((await f.owner.get('reports?type='+type)).rows[0].amount_paise,300);
 const voids=await f.owner.get('reports?type=voids');assert.equal(voids.rows[0].value_paise,owner.void_value_paise);
 await action(f,await f.owner.get('orders/'+o.id),'refund',{mode:'partial',method:'Cash',amountPaise:200,reason:'QA report refund'});assert.equal((await f.owner.get('reports?type=refunds')).rows[0].refund_type,'partial');
});
